export const API_ERROR = 'EVENT/API_ERROR_RECEIVED';
export const WEATHER_DATA_RECEIVED = 'EVENT/WEATHER_DATA_RECEIVED';
export const INITIAL_METRICS_RECEIVED = 'EVENT/INITIAL_METRICS_RECEIVED';
export const SET_SELECTED_METRICS = 'EVENT/SET_SELECTED_METRICS';
export const SET_INITIAL_METRIC_VALUE = 'EVENT/SET_INITIAL_METRIC_VALUE';
export const METRIC_VALUE_SUBSCRIPTION_RECEIVED = 'EVENT/METRIC_VALUE_SUBSCRIPTION_RECEIVED';
